[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "ising"
description = "Exploration into ising machines"
version = "0.1.0"
requires-python = ">=3.12.7"
dependencies = [
    "gurobipy<=12.0.0",
    "h5py<=3.12.1",
    "jax<=0.10.0",
    "matplotlib<=3.9.2",
    "networkx<=3.4.2",
    "numba<=0.61.2",
    "numpy<=1.26.4",
    "pandas<=2.3.0",
    "pyyaml<=6.0.2",
    "scipy<=1.11.4",
    "seaborn<=0.13.2",
    "shapely<=2.1.2",
    "tqdm<=4.67.1",
    "tsplib95<=0.7.1",
]

[tool.setuptools.packages.find]
include = ["ising*", "Paper_OpenIsing*"]

[tool.pytest.ini_options]
testpaths = "tests"
cache_dir = ".cache/pytest"

[tool.ruff]
src = ["ising", "tests"]
extend-exclude = ["ising/under_dev/"]
line-length = 120
indent-width = 4
cache-dir = ".cache/ruff"

[tool.ruff.lint]
#select = ["E4", "E7", "E9", "F"]
select = ["F", "E", "W", "UP", "PT", "TID252", "A", "PTH", "PLC", "PLE"]
ignore = ["PT", "E731"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]

[dependency-groups]
dev = [
    "pytest<=8.3.3",
    "pytest-randomly<=3.16.0",
    "ruff>=0.16.10",
]
